const ar = {
  'addNewProject':'اضف مشروع جديد',
  'fundRaised':'الأموال المجموعة',
  'totalBacked':'عدد عمليات الدعم',
  'noInvestedProjectsFound':'المعذره ، انت لم تقم بالاستثمار باي مشروع.',
  'noBookmarksFound':'المعذرة أنت لم تقم بحفظ أي مشروع في المفضلة.',
  'home':'الرئيسية',
  'investedProjects':'المشاريع المستثمر بها',
  'bookMark':'المفضلة',
  'profile':'الملف الشخصي',
  'projects':'المشاريع',
  'dashboard':'لوحة التحكم',
  'country':'الدولة',
  'amount':'القيمة',
  'fundingGoal':'هدف التمويل',
  'pledgesReceived':'عدد التعهدات المستلمة',
  'projectName':'اسم المشروع',
  'changeProfilePicture':'تغيير صورة الملف الشخصي',
  'basicInfo':'المعلومات الاساسية',
  'firstName':'الاسم الأول',
  'lastName':'اسم العائلة',
  'nationality':'الجنسية',
  'email':'البريد الالكتروني',
  'password':'كلمة المرور',
  'login':'تسجيل الدخول',
  'signIn':'تسجيل الدخول',
  'signOut':'تسجيل الخروج',
  'passowrdOrEmailIsNotCorrect':'البريد الالكتروني أو كلمة المرور غير صحيحة ، يرجى المحاولة مره أخرى .',
  'home':'الرئيسية',
  'aboutUs':'من نحن',
  'choosingUs':'لماذا نحن',
  'ourTeam':'فريقنا',
  "graphicsDesign":"رسم وتصميم",
  "digitalMarketing":"تسويق الكتروني",
  "writingAndranslation":'كتابة وترجمة',
  "videoAndAnimation":'رسوم متحركة وفيديوهات',
  "musicAndAudio":'اصوات وموسيقى',
  "programmingAndTech":'تكنولوجيا وبرمجة',
  "data":'بيانات', 


}
export default ar;