const ar = {
  'addNewProject':'اضف مشروع جديد',
  'fundRaised':'الأموال المجموعة',
  'totalBacked':'عدد عمليات الدعم',
  'noInvestedProjectsFound':'المعذره ، انت لم تقم بالاستثمار باي مشروع.',
  'noBookmarksFound':'المعذرة أنت لم تقم بحفظ أي مشروع في المفضلة.',
  'noProjectsFound':'المعذرة أنت لم تقم بنشر أي مشروع حتى الآن .',
  'home':'الرئيسية',
  'investedProjects':'المشاريع المستثمر بها',
  'bookMark':'المفضلة',
  'profile':'الملف الشخصي',
  'projects':'المشاريع',
  'dashboard':'لوحة التحكم',
  'country':'الدولة',
  'amount':'القيمة',
  'fundingGoal':'هدف التمويل',
  'pledgesReceived':'عدد التعهدات المستلمة',
  'projectName':'اسم المشروع',
  'changeProfilePicture':'تغيير صورة الملف الشخصي',
  'basicInfo':'المعلومات الاساسية',
  'firstName':'الاسم الأول',
  'lastName':'اسم العائلة',
  'nationality':'الجنسية',
  'email':'البريد الالكتروني',
  'password':'كلمة المرور',
  'login':'تسجيل الدخول',
  'signIn':'تسجيل الدخول',
  'signOut':'تسجيل الخروج',
  'passowrdOrEmailIsNotCorrect':'البريد الالكتروني أو كلمة المرور غير صحيحة ، يرجى المحاولة مره أخرى .',
  'home':'الرئيسية',
  'aboutUs':'من نحن',
  'choosingUs':'لماذا نحن',
  'ourTeam':'فريقنا',
  "graphicsDesign":"رسم وتصميم",
  "digitalMarketing":"تسويق الكتروني",
  "writingAndranslation":'كتابة وترجمة',
  "videoAndAnimation":'رسوم متحركة وفيديوهات',
  "musicAndAudio":'اصوات وموسيقى',
  "programmingAndTech":'تكنولوجيا وبرمجة',
  "data":'بيانات', 
  'projectList':'قائمة المشاريع',
  'rewardListIsEmpty':'لائحة الجوائز فارغة',
  'newProjectHasAddedSuccessfully':'تم اضافة مشروع جديد بنجاح.',
  'reviewProject':'معاينة المشروع',
  'title':'الاسم',
  'category':'التصنيف',
  'projectType':'نوع المشروع',
  'description':'الوصف',
  'shortIntro':'مقدمة قصيرة',
  'projectImage':'صورة المشروع',
  'compaignDurationEnd':'وقت انتهاء الحملة',
  'risksAndChallenges':'المخاطر و التحديات',
  'rewardList':'لائحة الجوائز',
  'projectHasUpdateSuccessfully':'تم تعديل المشروع بنجاح.',
  'authHasUpdatedSuccessfully':'تم تعديل معلومات الحساب بنجاح.',
  'profilePicture':'الصورة الشخصية',
  'confirm':'تأكيد',
  'close':'اغلاق',
  'add':'اضف',
  'projectsBacked':'المشاريع المدعومة',
  'browseProjects':'تصفّح المشاريع',
  'raised':'المجموع',
  'goal':'الهدف',
  'explore':'استكشف',
  'daysLeft':'يوم متبقي',
  'crowdfundingPlatform':'منصة التمويل الجماعي',
  'slogan':'نساعدك في كل خطوة ، من المفاهيم الأساسية وحتى النجاح .',
  'share':'نشر',
  'backProject':'دعم المشروع',
  'story':'القصة',
  'commentsList':'لائحة التعليقات',
  'selectReward':'اختر الجائزة',
  'searchForProject':'ابحث عن مشروع',
  'noResultFound':'نعتذر ، لم يتم العثور على أي نتيجة ، يرجى ادخال كلمة بحث اخر.'

}
export default ar;