const en = {
    'addNewProject':'Add new project',
    'fundRaised':'Fund Raised',
    'totalBacked':'Total backed',
    'noInvestedProjectsFound':'Sorry you didn\'t invest in any project yet.',
    'noBookmarksFound':'Sorry you didn\'t save any project yet.',
    'home':'Home',
    'investedProjects':'Invested projects',
    'bookMark':'BookMark',
    'profile':'Profile',
    'projects':'Projects',
    'dashboard':'Dashboard',
    'country':'country',
    'amount':'amount',
    'fundingGoal':'funding goal',
    'pledgesReceived':'pledges received',
    'projectName':'project name',
    'changeProfilePicture':'Change Profile Picture',
    'basicInfo':'Basic Info',
    'firstName':'first name',
    'lastName':'last name',
    'nationality':'nationality',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
}

export default en;