const en = {
    'addNewProject':'Add new project',
    'fundRaised':'Fund Raised',
    'totalBacked':'Total backed',
    'noInvestedProjectsFound':'Sorry you didn\'t invest in any project yet.',
    'noBookmarksFound':'Sorry you didn\'t save any project yet.',
    'home':'Home',
    'investedProjects':'Invested projects',
    'bookMark':'BookMark',
    'profile':'Profile',
    'projects':'Projects',
    'dashboard':'Dashboard',
    'country':'country',
    'amount':'amount',
    'fundingGoal':'funding goal',
    'pledgesReceived':'pledges received',
    'projectName':'project name',
    'changeProfilePicture':'Change Profile Picture',
    'basicInfo':'Basic Info',
    'firstName':'first name',
    'lastName':'last name',
    'nationality':'nationality',
    'email':'email',
    'password':'password',
    'login':'Login',
    'signIn':'sign in',
    'signOut':'sign out',
    'passowrdOrEmailIsNotCorrect':'Password or email isn\'t correnct.',
    'home':'Home',
    'aboutUs':'About us',
    'choosingUs':'Choosing us',
    'ourTeam':'Our team',
    "graphicsDesign":"Graphics & Design",
    "digitalMarketing":"Digital Marketing",
    "writingAndranslation":'Writing & Translation',
    "videoAndAnimation":'Video & Animation',
    "musicAndAudio":'Music & Audio',
    "programmingAndTech":'Programming & Tech',
    "data":'Data', 
}

export default en;
