const en = {
    'addNewProject':'Add new project',
    'fundRaised':'Fund Raised',
    'totalBacked':'Total backed',
    'noInvestedProjectsFound':'Sorry you didn\'t invest in any project yet.',
    'noBookmarksFound':'Sorry you didn\'t save any project yet.',
    'noProjectsFound':'Sorry you didn\'t have any project published yet.',
    'home':'Home',
    'investedProjects':'Invested projects',
    'bookMark':'BookMark',
    'profile':'Profile',
    'projects':'Projects',
    'dashboard':'Dashboard',
    'country':'country',
    'amount':'amount',
    'fundingGoal':'funding goal',
    'pledgesReceived':'pledges received',
    'projectName':'project name',
    'changeProfilePicture':'Change Profile Picture',
    'basicInfo':'Basic Info',
    'firstName':'first name',
    'lastName':'last name',
    'nationality':'nationality',
    'email':'email',
    'password':'password',
    'login':'Login',
    'signIn':'sign in',
    'signOut':'sign out',
    'passowrdOrEmailIsNotCorrect':'Password or email isn\'t correnct.',
    'home':'Home',
    'aboutUs':'About us',
    'choosingUs':'Choosing us',
    'ourTeam':'Our team',
    "graphicsDesign":"Graphics & Design",
    "digitalMarketing":"Digital Marketing",
    "writingAndranslation":'Writing & Translation',
    "videoAndAnimation":'Video & Animation',
    "musicAndAudio":'Music & Audio',
    "programmingAndTech":'Programming & Tech',
    "data":'Data', 
    'rewardListIsEmpty':'Reward list is empty',
    'newProjectHasAddedSuccessfully':'New project added successfully.',
    'reviewProject':'Review a project',
    'title':'title',
    'category':'category',
    'projectType':'project type',
    'description':'description',
    'shortIntro':'short intro',
    'projectImage':'project image',
    'compaignDurationEnd':'compaign duration end',
    'risksAndChallenges':'risks and challenges',
    'rewardList':'reward list',
    'projectHasUpdatedSuccessfully':'Project has updated successfully',
    'authHasUpdatedSuccessfully':'Profile info has updated successfully',
    'profilePicture':'Profile picture',
    'confirm':'confirm',
    'close':'close',
    'add':'add',
    'projectsBacked':'Projects backed',
    'browseProjects':'Browse projects',
    'raised':'Raised',
    'goal':'Goal',
    'explore':'Explore',
    'daysLeft':'Days left',
    'crowdfundingPlatform':'Crowdfunding Platform',
    'slogan':'We Help at Every Step From Concept to Market.',
    'share':'share',
    'backProject':'Back project',
    'story':'Story',
    'commentsList':'Comments list',
    'selectReward':'Select Reward',

}

export default en;
