const sw = {
    'addNewProject':'',
    'fundRaised':'',
    'totalBacked':'',
    'noInvestedProjectsFound':'',
    'noBookmarksFound':'',
    'home':'',
    'investedProjects':'',
    'bookMark':'',
    'profile':'',
    'projects':'',
    'dashboard':'',
    'country':'',
    'amount':'',
    'fundingGoal':'',
    'pledgesReceived':'',
    'projectName':'',
    'changeProfilePicture':'',
    'basicInfo':'Basic Info',
    'firstName':'first name',
    'lastName':'last name',
    'nationality':'nationality',
}

export default sw;