const sw = {
    'noBookmarksFound':'',
    'addNewProject':'Ongeza mradi mpya',
    'fundRaised':'Kilichopatikana kwenye mfuko',
    'totalBacked':'Jumla ya waliounga mkono',
    'noInvestedProjectsFound':'Samahani, hujawekeza kwenye mradi wowote.',
    'noBookmarksFound':'Samahani, hamna hifadhi ya mradi wowote.',
    'home':'Nyumbani',
    'investedProjects':'Miradi uliyowekeza',
    'bookMark':'kitabu cha hifadhi ya tovuti',
    'profile':'Akaunti',
    'projects':'Mradi',
    'dashboard':'Dashibodi',
    'country':'nchi',
    'amount':'kiasi',
    'fundingGoal':'lengo la kiasi cha mfuko',
    'pledgesReceived':'ahadi zilizopokelewa',
    'projectName':'jina la mradi',
    'changeProfilePicture':'Badilisha picha ya Akaunti',
    'projectName':'',
    'changeProfilePicture':'',
    'basicInfo':'',
    'firstName':'',
    'lastName':'',
    'nationality':'',
    'email':'',
    'password':'',
    'login':'',
    'signIn':'',
    'signOut':'',
    'passowrdOrEmailIsNotCorrect':'',
    'home':'',
    'aboutUs':'',
    'choosingUs':'',
    'ourTeam':'',
    "graphicsDesign":'',
    "digitalMarketing":'',
    "writingAndranslation":'',
    "videoAndAnimation":'',
    "musicAndAudio":'',
    "programmingAndTech":'',
    "data":'', 
    'rewardListIsEmpty':'',
    'newProjectHasAddedSuccessfully':'',
    'noProjectsFound':'',
    'reviewProject':'',
    'title':'',
    'category':'',
    'projectType':'',
    'description':'',
    'shortIntro':'',
    'projectImage':'',
    'compaignDurationEnd':'',
    'risksAndChallenges':'',
    'rewardList':'',
    'projectHasUpdateSuccessfully':'',
    'authHasUpdatedSuccessfully':'',
    'profilePicture':'',
    'confirm':'',
    'close':'',
    'add':'',
    'projectsBacked':'',
    'browseProjects':'',
    'raised':'',
    'goal':'',
    'explore':'',
    'daysLeft':'',  
    'crowdfundingPlatform':'',
    'slogan':'',
    'share':'',
    'backProject':'',
    'story':'',
    'commentsList':'',
    'selectReward':'',
    'searchForProject':'',
    'noResultFound':''
  
}

export default sw;

