const tkm = {
    'addNewProject':'',
    'fundRaised':'',
    'totalBacked':'',
    'noInvestedProjectsFound':'',
    'noBookmarksFound':'',
    'home':'',
    'investedProjects':'',
    'bookMark':'',
    'profile':'',
    'projects':'',
    'dashboard':'',
    'country':'',
    'amount':'',
    'fundingGoal':'',
    'pledgesReceived':'',
    'projectName':'',
    'changeProfilePicture':'',
    'basicInfo':'',
    'firstName':'',
    'lastName':'',
    'nationality':'',
    'projectList':'',
}

export default tkm;